# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

# Shared configuration for all resources, more in
# https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # The PermissionsBoundary allows users to safely develop with their function's permissions constrained
    # to their current application. All the functions and roles in this application have to include it and
    # it has to be manually updated when you add resources to your application.
    # More information in https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html
    Environment:
      Variables:
        ENV: 
          Ref: Env
        PUBLIC_BUCKET:
          Ref: publicBucket
        PRIVATE_BUCKET:
          Ref: privateBucket
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'

Parameters:
  AppId:
    Type: String
  Env:
    Type: String
    Description: Indicated the enviroment the application is deployed to.
  publicBucket:
    Type: String
    Default: aws-${AWS::Region}-${AWS::AccountId}-${AppId}-simpleappbucket
    Description: Public bucket that recieves the files.
  privateBucket:
    Type: String
    Default: aws-${AWS::Region}-${AWS::AccountId}-${AppId}-securedappbucket
    Description: Private bucket that we save the files in.

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: incomingPDFHandler.js
  incomingPDFHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/incoming-pdf-handler.incomingPDFHandler
      Runtime: nodejs10.x
      FunctionName: !Sub "primalPDFHandler"
      Description: A Lambda function that listens to S3 public bucket and save pdf files' data
      MemorySize: 128
      Timeout: 60
      Policies:
        # Give Read Permissions to the S3 Bucket
        - S3ReadPolicy:
            BucketName: !Sub aws-${AWS::Region}-${AWS::AccountId}-${AppId}-simpleappbucket
        - S3WritePolicy:
            BucketName: !Sub aws-${AWS::Region}-${AWS::AccountId}-${AppId}-securedappbucket
      Events:
        simpleappbucketEvent:
          Type: S3
          Properties:
            Bucket: !Ref simpleappbucket
            Events: s3:ObjectCreated:*
            #Filter:
             # S3Key:
              #  Rules:
               #   - Name: suffix
                #    Value: ".json"
  innerHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/inner-handler.innerHandler
      Runtime: nodejs10.x
      FunctionName: !Sub "innerPDFHandler"
      Description: A Lambda function that listens to S3 public bucket and save pdf files' data
      MemorySize: 128
      Timeout: 60
      Policies:
        # Give Read Permissions to the S3 Bucket
        - S3ReadPolicy:
            BucketName: !Sub aws-${AWS::Region}-${AWS::AccountId}-${AppId}-simpleappbucket
        - S3WritePolicy:
            BucketName: !Sub aws-${AWS::Region}-${AWS::AccountId}-${AppId}-securedappbucket
      Events:
        simpleappbucketEvent:
          Type: S3
          Properties:
            Bucket: !Ref simpleappbucket
            Events: s3:ObjectCreated:*
            #Filter:
             # S3Key:
              #  Rules:
               #   - Name: suffix
                #    Value: ".json"
  simpleappbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub aws-${AWS::Region}-${AWS::AccountId}-${AppId}-simpleappbucket
  securedappbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub aws-${AWS::Region}-${AWS::AccountId}-${AppId}-securedappbucket
